### ISSUE TITLE
JSON being generated, but so is a build folder with HTML

### ISSUE THREAD

**Issue by lokesh** [klaytonfaria/markdown-json#4]
When running markdown-json, I get the appropriate json file output, but I also see a `build` folder with `html` being generated.

_notes-to-json.js_
```
const markdownJson = require('markdown-json');

const settings = {
        name: 'notes-json',
      	cwd: './',
      	src: './src',
        filePattern: 'notes/*.md',
        ignore: "*(icon|input)*",
        dist: './src/data/notes.json',
        server: false,
        port: 3001
      };

markdownJson(settings).then((data) => {
  console.log('data:', data);
}).catch((err) => {
  console.log('error:', err);
})
```

Example Markdown file:

_src/notes/tokyo-story.md_
```
---
type: movie
title: Tokyo Story
creator: Yasujiro Ozu
date: 1953
image: tokyo-story.jpg
rating: 5
note-date: April 2, 2019
---

It's a simple story of parents visiting their grown up children. The pace is not hurried. The delivery from the actors is straightforward, not melodramatic. The camera moves in one shot, otherwise it stays still. Yet, in this calm, the movie elicits deeply intense feelings.

Ozu captures the relationship between parents and their children in a way I've never seen or felt before. It hits hard. The movie has aged amazingly well over 60 years and the issues of generational differences and familial relationships it tackles are still present.
This goes straight into my favorite movies of all-time list! Which is rare from a first viewing.
```

JSON output works. But I also see the following folders and html file being generated:
![image](https://user-images.githubusercontent.com/51469/63205862-970abc00-c05f-11e9-9c1f-b133ef938a49.png)

Is this expected behavior? Any way to disable?

Thanks ahead of time and for the work on this project, and let me know if you need any other context.

**Comment by lokesh** [comment]
Just looked at the project source code and saw that you are using Metalsmith behind the scenes. It looks like that is the culprit of the `build/` folder:
https://github.com/klaytonfaria/markdown-json/blob/73adba1ec4646d20fd35915bfee2be4b6995ac0c/lib/generator.js#L96

It can be quite problematic. In my case, I had a preexisting `build/` folder with build files that were then deleted.

**Comment by lokesh** [comment]
One solution would be to output the html generated by Metalsmith into a temp location and then clean it up after.

**Comment by klaytonfaria** [comment]
Hi @lokesh, thanks for your feedback! I'll work on this issue!!
